name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --output-path docs --base-href /
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: docs/.
          dst_path: /.
          dst_owner: chimera-development
          dst_repo_name: chimera-development.github.io
          dst_branch: main
          src_branch: main
