name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Build & Deploy to branch
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npm install
          npm run ng -- deploy --name="markm001" --email="markchrim@gmail.com"
